V = zeros(360,360,length(bestVs));
for j=1:length(bestVs)
    V(:,:,j) = v2m(bestVs{j});
end

hold on 
for j=1:length(bestVs)
    v= V(:,:,j);
    plot(v(:))
end
hold off 

load('Data\Atlas_Anatomical\tess_cortex_mid_high_8000V_fix.mat');
load('Data\Avarege_Conn&Tract_ROISpace\averageConnectivity_tractLengths.mat');
load('Data\Avarege_Conn&Tract_ROISpace\averageConnectivity_Fpt.mat');
%load('Data\Model_Parameters\parameters.mat');
load('Data\Average_Velocity_ROISpace\averageDelays_FTRACTS.mat')
% Align the data with the HCP-MMP1.0 Atlas generated by Brainstorm
Labels_Atlas = cell(1, 360);
for j = 1:360
    Labels_Atlas{j} = selectBeforeSecondUnderscore(Atlas(iAtlas).Scouts(j).Label);
end

Labels_Tracts = parcelIDs;  
N = length(Labels_Atlas);

%% Correcting the Length of the Tracts Matrix

% % Reference: Rosen BQ, Halgren E (2022) An estimation of the absolute number
% % of axons indicates that human cortical areas are sparsely connected. PLoS
% % Biol 20(3): e3001575. https://doi.org/10.1371/journal.pbio.3001575
% disp ("-->> Correcting the Tracts Matrix by the Atlas");
% corrected_tractLengths = zeros(N, N);
% new_order = [];
% for i = 1:360
%     target_Atlas_label = Labels_Atlas{i};
%     for j = 1:360
%         if strcmpi(target_Atlas_label, Labels_Tracts{j})
%             new_order = [new_order, j];
%         end
%     end
% end
% 
% corrected_tractLengths = tractLengths(new_order, new_order);
% 
% ages = linspace(10, 100, 200);
% [X, Y] = meshgrid(ages, corrected_tractLengths(:));
% Z = zeros(size(X)); % Initialize the matrix to store regression results
% 
% for i = 1:size(V, 1)
%     for j = 1:size(V, 2)
%         v_elements = squeeze(V(i, j, :)); % Extract the vector of V elements for the current (i,j)
%         % Perform regression (assuming linear regression for simplicity)
%         mdl = fitlm([ages(:), corrected_tractLengths(:)], v_elements);
%         Z(i, j) = mdl.Coefficients.Estimate(1); % Example of storing the intercept (you can choose another coefficient)
%     end
% end
% 
% % Plotting the surf
% figure;
% surf(X, Y, Z);
% xlabel('Age');
% ylabel('Tract Length');
% zlabel('Regressed V Value');
% title('Regression of V Elements with respect to Age and Tract Length');


disp("-->> Correcting the Tracts Matrix by the Atlas");
corrected_tractLengths = zeros(N, N);
new_order = [];
for i = 1:360
    target_Atlas_label = Labels_Atlas{i};
    for j = 1:360
        if strcmpi(target_Atlas_label, Labels_Tracts{j})
            new_order = [new_order, j];
        end
    end
end

corrected_tractLengths = tractLengths(new_order, new_order);

ages = linspace(10, 100, 200);
delays = zeros(size(V, 1), 1); % Initialize the matrix to store regression results for delays

% Loop through each pair (i, j)
for i = 1:size(V, 1)
    for j = 1:size(V, 2)
        v_elements = squeeze(V(i, j, :)); % Extract the vector of V elements for the current (i,j)
        % Perform linear regression with respect to age only
        mdl = fitlm(ages(:), v_elements);
        % Store the coefficient corresponding to age (slope) or intercept based on what you want to analyze
        delays(i, j) = mdl.Coefficients.Estimate(2); % Slope of the regression line (indicating how delay changes with age)
    end
end

% Plotting the result
figure;
plot(ages, mean(delays, 2)); % Plot the average delays across pairs for each age
xlabel('Age');
ylabel('Average Delay');
title('Variation of Delays with Age');
grid on;

